### PR TITLE
REL: v0.0.2

### PR DESCRIPTION
**Pull request by dmgav**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin please add user @dmgav

### CODE REVIEW

**Comment by dmgav** [comment]
@conda-forge-admin, please rerender

**Comment by dmgav** [comment]
@conda-forge-admin, please update team

**Comment by dmgav** [comment]
@mrakitin Could you try merging this PR?

**Comment by mrakitin** [comment]
Looks like the ownership of the repo is broken, I don't see the button either!
image

@conda-forge/core, could you please fix the ownership for us?

**Comment by beckermr** [comment]
In the future just make an issue like this: https://github.com/conda-forge/bluesky-queueserver-api-feedstock/issues/3

Any one can do that and our admin service will fix permissions.

**Comment by beckermr** [comment]
you also need to accept invites to conda-forge if you have not

**Comment by mrakitin** [comment]
Thanks, @beckermr! Noted, will use this command if I experience a similar issue in the future.

**Pull request merged**
